### ISSUE TITLE
npm run enclave-build hangs

### ISSUE THREAD

**Issue by levithomason** [eanplatter/enclave#101]
Running `npm run enclave-build` produces this output and never finishes.  I did minimal debugging but couldn't find the issue yet.

``` shell
› npm run enclave-build 

> arena@0.0.1 enclave-build /Users/levithomason/src/arena
> node node_modules/enclave/src/build.js
```

Here is my version info:

``` shell
› npm -v
3.8.2

› node -v
v5.9.0

› cat node_modules/enclave/package.json| json version
0.10.3

› uname -mrs
Darwin 14.5.0 x86_64
```

**Comment by eanplatter** [comment]
Weird, it's something specific with your project (still probably an enclave bug). I tried to recreate the error on a fresh enclave project and it works correctly. I also tried it on the arena project you referenced (because I happen to have been working on the same repo), and I can recreate the bug. Is arena doing anything weird on build compiling?

**Comment by levithomason** [comment]
Not that I know of, I believe you started the Arena project.

**EDIT**

I'm refactoring a lot on Arena, let's see if the issue holds up after the refactors.  Then we can dig in and diagnose.

**Comment by levithomason** [comment]
Can't stand stale issues, so closing.  If this persists or becomes a problem, it will come up again.
