### ISSUE TITLE
Including css and js from node_modules

### ISSUE THREAD

**Issue by spoeken** [eanplatter/enclave#36]
How would you do this? Since it's dir down from src I can't include from index.html.

**Comment by spoeken** [comment]
Alternatively, what is needed to import or require in App.js?

**Comment by FiberJW** [comment]
all you do is `require()` the module name in your css like any other node module.

**Comment by FiberJW** [comment]
It'll get run through the css loader and included in the main index_bundle.js file

**Comment by FiberJW** [comment]
or if the module doesn't export a main css file just `require('../node_modules/<modulename>/<styles_dir>/index.css` or whatever the folder structure is. Basically use a relative path is what i'm saying

**Comment by eanplatter** [comment]
There's a lot of different paradigms on how you might do css in a React app. Since React isn't DOM-centric the normal way of doing things with your `index.html` file is a little skewed. 

Check out the `example/` directory where we're using a `.scss` file:
https://github.com/eanplatter/enclave/blob/master/example/components/Example.jsx

Here's the code:

``` jsx

import React, { PropTypes } from 'react'
import ENV from '../env.json'
import '../styles/example.scss'

class Example extends React.Component {
  render () {
    return (
      <div className='example'>
        <img src='http://bit.ly/1YEe536'/>
        <h1>
          Example
        </h1>
        <pre>
          {JSON.stringify(ENV)}
        </pre>
        <p>SCSS and JSX Works Too</p>
      </div>
    )
  }
}

export default Example
```

By importing the `.scss` file we end up with the classes lined out in that file, and we're able to use them.

The cool thing about this is that specificity issues with css are avoided because we can make really modular stylesheets. No other react component should be aware of those styles unless they're imported into the file.

If at the end of the day you still want a stylesheet linked into your 'index.html', just be aware (like you mentioned) that the actual `index.html` file is in your output directory (dist) and you'll have to change to relative path to account for that.

CDNs on the other hand work great, since their path is a url, you can just add them to your index.html file and they're available. So something like bootstrap or foundation is easily accessible.

**Comment by eanplatter** [comment]
@spoeken closing for now, let me know if you have any other questions.
