### ISSUE TITLE
[Discussion] How does this project differ from a yeoman generator?

### ISSUE THREAD

**Issue by mcMickJuice** [eanplatter/enclave#47]
First off, I'm not trolling.  I think that we can all agree that getting webpack up and running with transpilation (which is needed if you use jsx and react) is a pain and that there's a learning curve. However I fail to see much of a difference between how this project can be of a benefit when we have yeoman generators.  For example, [this generator](https://github.com/newtriks/generator-react-webpack) will get you up and running with react and webpack and hot reloading AND includes component generation if that strikes your fancy.

Again, I'm not trying to troll, I'd just like to hear @eanplatter 's vision on where he wants to go with this project.

**Comment by FiberJW** [comment]
Yeoman _generates_. Enclave _alleviates_. Enclave is made to help a user get up and running quickly, and so does Yeoman. But Enclave generates no project code. It just sets up all of the user configs like babel and webpack and hot reloading without any boilerplate. It's mean to be a buttery smooth `npm install --save enclave` and get to work. :+1:

**Comment by eanplatter** [comment]
The main reason I don't like generators is that you end up with a lot of boilerplate. It's hard to maintain an app when a lot of the foundational code was written by someone else. 

Enclave is is trying to balance between being as unobtrusive as possible and as helpful as possible.

**Comment by eanplatter** [comment]
Sorry didn't mean to close that, I was on mobile and pushed the wrong button.

I used to teach at a code school and when I first got there they taught the students Angular, but all of the Angular projects were built with Yeoman.

I saw soooooooo many crazy code issues because you had people with generated code in their apps they didn't understand. It's kind of akin to having someone come over and write a boilerplate for your app, and then you finish the rest. It's like having automatic legacy code :P

In a situation like that, if something is legitimately broken it's hard to tell if it's my code or my yeoman generators code.

With enclave, if something is actually broken, enclave can fix itself. 

Yeoman generators are great if you know what you're doing, but if your a beginner they are more trouble than they're worth.

And even some experienced developers don't enjoy having someone else's code in their app, myself included.

**Comment by eanplatter** [comment]
@mcMickJuice great question though, perhaps we maybe should add FAQ to the readme for good questions like that.

**Comment by mcMickJuice** [comment]
Understood (and I agree with your sentiments on yeoman including too much boilerplate). 

So enclaves sole purpose is to abstract away the build/transpiling tooling of an app, regardless of the technologies that it is building?  Just in the immediate future, we're focusing on react as the primary technology that users will use to build apps.

Got it.

**Comment by eanplatter** [comment]
Yup! Thanks again! Gonna close this for real this time ;)
